### ISSUE TITLE
Is there any docs on how to run the Text to Speech?

### ISSUE THREAD

**Issue by DamienDeepgram** [haoheliu/AudioLDM2#29]
I saw there are example outputs [here](https://audioldm.github.io/audioldm2/#section_3)

But there is no info how to run Text to Speech in the documentation

eg.

In a man's voice say "hello world"
In a women's say "hello world"

**Comment by haoheliu** [comment]
The text-to-speech part is here: https://github.com/haoheliu/AudioLDM2#run-the-model-in-commandline 
e.g.:
```shell
audioldm2 -t "A female reporter is speaking full of emotion" --transciption "Wish you have a good day"
```

**Comment by binglel** [comment]
Do this,
audioldm2 -t "A female reporter is speaking full of emotion" --transciption "Wish you have a good day"

Sorry, I encountered an error：
audioldm2: error: unrecognized arguments: --transciption

**Comment by EscaticZheng** [comment]
--transcription. Missing "r".There is a misspelling in doc.

**Comment by DamienDeepgram** [comment]
Not sure how I missed this thanks

**Comment by Tortoise17** [comment]
How to provide the reference sample to take that accent and generate speech ? If you can give a hint or guide would be great.
