### ISSUE TITLE
Cannot import name 'AudioLDM2Pipeline' from 'diffusers

### ISSUE THREAD

**Issue by AB00k** [haoheliu/AudioLDM2#34]
having an issue while trying to run the checkpoint from hugging face:

ImportError                               Traceback (most recent call last)
[<ipython-input-4-94ba01436d9c>](https://localhost:8080/#) in <cell line: 3>()
      1 import scipy
      2 import torch
----> 3 from diffusers import AudioLDM2Pipeline
      4 from IPython.display import Audio
      5 

ImportError: cannot import name 'AudioLDM2Pipeline' from 'diffusers' (/usr/local/lib/python3.10/dist-packages/diffusers/__init__.py)

**Comment by kty4119** [comment]
I solved it with the code below.

!pip install --quiet --upgrade git+https://github.com/huggingface/diffusers.git git+https://github.com/huggingface/transformers.git accelerate

**Comment by AB00k** [comment]
Thanks buddy!
