### ISSUE TITLE
RuntimeError("Windows not yet supported for torch.compile") RuntimeError: Windows not yet supported for torch.compile

### ISSUE THREAD

**Issue by JayDeeRC** [haoheliu/AudioLDM2#4]
having issues even manually going through and installing dependencies.

**Comment by ohmygoobness** [comment]
what GPU do you have? I saw a 15.7Gb VRAM usage, I got it workaround by commenting line 28 in app.py `# audioldm = torch.compile(audioldm)`

**Comment by JayDeeRC** [comment]
> what GPU do you have? I saw a 15.7Gb VRAM usage, I got it workaround by commenting line 28 in app.py `# audioldm = torch.compile(audioldm)`

Thanks! I have a 3090. Went in and commented it out but also had to uninstall / reinstall packages. got it working eventually.

run 
pip uninstall torch -y
pip uninstall torchvision -y
pip uninstall torchaudio -y

then
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
+ 
pip install -U --pre xformers

then with line 28 commented out it should boot.
