### ISSUE TITLE
Can't load tokenizer for 'roberta-base'. 

### ISSUE THREAD

**Issue by hello-xiaow** [haoheliu/AudioLDM2#47]
请问出现这种情况如何处理呢？目前自己没找到解决方案。尝试重新按照流程安装，依然出现这个问题。
OSError: Can't load tokenizer for 'roberta-base'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'roberta-base' is the correct path to a directory containing all relevant files for a RobertaTokenizer tokenizer.

**Comment by Zq5437** [comment]
可以试一下把魔法开全局，是否可以解决？我之前也是这个问题，但是开完后就可以了，之前我一直访问不了huggingface.co这个网站，可能是在本地允许访问，但是速度很慢，所以出不来

**Comment by hello-xiaow** [comment]
> 可以试一下把魔法开全局，是否可以解决？我之前也是这个问题，但是开完后就可以了，之前我一直访问不了huggingface.co这个网站，可能是在本地允许访问，但是速度很慢，所以出不来

非常感谢！
