### ISSUE TITLE
Unable to run on Mac M1

### ISSUE THREAD

**Issue by glovebx** [haoheliu/AudioLDM2#6]
AssertionError: Torch not compiled with CUDA enabled

Any plans to support Mac M1?

**Comment by Swallow74** [comment]
Same here... :(

**Comment by microboym** [comment]
I modified some code for MPS support and created a pr.

**Comment by Swallow74** [comment]
Thank you very much, i'll try as sono as possibile.

**Comment by robertZaufall** [comment]
> I modified some code for MPS support and created a pr.  

it's working on my system: MacBook Pro M2 Max 96 GB.  
````
1.03s/it using audioldm2-full-large-650k
2.21s/it using audioldm2-full
````
I had to set env variable `PYTORCH_ENABLE_MPS_FALLBACK=1` according to an error message I got.

**Comment by microboym** [comment]
@robertZaufall Well, because currently Pytorch hasn't support some operations on MPS, the variable is required. After Pytorch support those ops the var can be removed.

**Comment by robertZaufall** [comment]
> @robertZaufall Well, because currently Pytorch hasn't support some operations on MPS, the variable is required. After Pytorch support those ops the var can be removed.

While the commandline is working now, the Gradio app results in an error on my system:  
`"TypeError: Cannot convert a MPS Tensor to float64 dtype as the MPS framework doesn't support float64. Please use float32 instead."`

**Comment by microboym** [comment]
I have not try the Gradio app yet. But the error had appeared when I was debugging the command line code. I fix it by adding conversion from `float64` to `float32` when MPS is used.

**Comment by microboym** [comment]
I just found that in `class DDIMSampler(object)`, the type of `self.device` jumps from `str` to `torch.device` from time to time, which means I have to adapt my previous solution that only consider the `str` circumstances to this:
```python
is_mps = self.device == "mps" or self.device == torch.device("mps")
if is_mps and attr.dtype==torch.float64:
    attr = attr.to(self.device, dtype=torch.float32)
else:
    attr = attr.to(self.device)
```
I'll push it a minute later.

**Comment by robertZaufall** [comment]
> I just found that in `class DDIMSampler(object)`, the type of `self.device` jumps from `str` to `torch.device` from time to time, which means I have to adapt my previous solution that only consider the `str` circumstances to this:
> 
> ```python
> is_mps = self.device == "mps" or self.device == torch.device("mps")
> if is_mps and attr.dtype==torch.float64:
>     attr = attr.to(self.device, dtype=torch.float32)
> else:
>     attr = attr.to(self.device)
> ```
> 
> I'll push it a minute later.

awesome! it's working now 😃
