### ISSUE TITLE
cannot import name 'VitsModel' from 'transformers'

### ISSUE THREAD

**Issue by XinleiNIU** [haoheliu/AudioLDM2#75]
Hi,

I got a problem said 
```
cannot import name 'VitsModel' from 'transformers'
```
My transformers version is 4.30.2. Any ideas for solving this? Thank you.

**Comment by tolotrasamuel** [comment]
What is the solution ?

**Comment by XinleiNIU** [comment]
> What is the solution ?

I did not use the conda venv but a python venv and then install requirement.txt. The problem just magiclly been fixed, I have no idea with this.

**Comment by drewgrant** [comment]
I'm also having this issue now even though everything was working previously. I am using the same conda env that I previously used with no issues. My transformers version is 4.30.2 just like the requirements.txt file specifies. 

Update: I reran the Diffusers and Transformers installation command (pip install --upgrade git+https://github.com/huggingface/diffusers.git transformers accelerate ) and got rid of this error. Also, I will note that running that command installs transformers version 4.49.0.
